name: Stream Movies

on:
  schedule:
    - cron: "0 */5 * * *"  # Runs every 5 hours
  workflow_dispatch:  # Allows manual start

jobs:
  stream:
    runs-on: ubuntu-latest
    timeout-minutes: 0  # Disables timeout

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install FFmpeg
        run: sudo apt update && sudo apt install -y ffmpeg

      - name: Run Movie Streaming Script
        run: |
          while true; do
            python3 stream.py
            sleep 5
          done
